# Generated by Django 6.1.1 on 2026-09-28 11:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Например: 'Установка стиральной машины' (минимум 5 символов)", max_length=200, validators=[django.core.validators.MinLengthValidator(5, message='Название услуги должно содержать минимум 5 символов!')], verbose_name='Название услуги')),
                ('description', models.TextField(help_text='Что конкретно входит в работу', verbose_name='Описание услуги')),
                ('category', models.CharField(choices=[('repair', 'Ремонт'), ('cleaning', 'Уборка'), ('education', 'Обучение'), ('beauty', 'Красота'), ('it', 'IT'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Базовая цена должна быть больше нуля!')], verbose_name='Базовая цена (сом/руб)')),
                ('discount', models.PositiveIntegerField(default=0, help_text='Скидка для клиентов от 0% до 90%', validators=[django.core.validators.MinValueValidator(0, message='Скидка не может быть меньше 0%'), django.core.validators.MaxValueValidator(90, message='Скидка не может превышать 90%!')], verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Статус доступности услуги: принимает ли мастер заказы сейчас', verbose_name='Принимаю заказы сейчас')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Автор (мастер)')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Каталог услуг',
                'ordering': ['-created_at'],
            },
        ),
    ]
