# Generated by Django 6.1.1 on 2026-09-28 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Как обращаться к клиенту', max_length=150, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(help_text='Номер телефона для связи', max_length=30, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (например, +996 555 123456).', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Контактный телефон')),
                ('comment', models.TextField(blank=True, help_text='Адрес вызова мастера или удобное время', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service', verbose_name='Выбранная услуга')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
